import {OrganizationPublic} from "../organization";

export interface StartSettings {
  AutoCalculateMemberMoney: boolean;
  CreateUserBody: string;
  CreateUserSubject: string;
  CreateUserTitle: string;
  CreationDate: string;
  EndBookYear: string;
  GroupsSet: boolean;
  Id: number;
  InvoiceFileName: string;
  InvoiceMailContent: string;
  InvoiceMailSubject: string;
  InvoiceNr: number;
  InvoiceTemplatePath: string;
  JuristicStatut: number;
  JuristicStatute: null;
  MemberPublicAccessInvitationAutomatic: boolean;
  MemberPublicAccessInvitationContent: string;
  MemberPublicAccessInvitationMailSettings: string;
  MemberPublicAccessInvitationMailSettingsId: number;
  MemberPublicAccessInvitationSubject: string;
  MemberPublicAccessInvitationTtitle: string;
  MemberPublicAccessNotify: boolean;
  MemberPublicAccessNotifyPerson: string;
  MemberPublicAccessNotifyPersonId: number;
  MemberPublicAccessType: number;
  Organization: OrganizationPublic;
  OrganizationId: number;
  PaidMemberMoneyContent: string;
  PaidMemberMoneySubject: string;
  PaidMemberMoneyTitle: string;
  PayMemberMoneyContent: string;
  PayMemberMoneyOnline: boolean;
  PayMemberMoneySubject: string;
  PayMemberMoneyTitle: string;
  PublicAccessBackgroundColor: string;
  PublicAccessLogo: string;
  PublicAccessLogoSponsors: string;
  SkipGroup: boolean;
  SkipMemberMoney: boolean;
  SortGroup: {Id: number, Name: string};
  SortGroups: number;
  SortOrganisation: number;
  SortOrganization: {Id: number, Name: string};
  StartBookYear: string;
  UseGroups: boolean;
  UserId: number;
  WaitingListConfirmMail: string;
  WaitingListConfirmSubject: string;
  WaitingListIntro: string;
  WaitingListIntroText: string;
  WaitingListThankYouPageContent: string;
  WaitingListThankYouPageTitle: string;
}
